fix failing machines

diff --git a/utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml b/utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml
--- a/utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml
+++ b/utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml
@@ -14,13 +14,19 @@ lang_variant:
           rbenv install 3.0.2 --verbose
           rbenv global 3.0.2
           DD_INSTRUMENT_SERVICE_WITH_APM=false gem install bundler -v '~> 2.3.27'
-        
+
       - os_type: linux
         os_distro: rpm
         remote-command: |
           sudo yum remove rubygem-bundler || true
           sudo yum install -y gcc libyaml-devel curl
           sudo yum install openssl-devel -y
+          if ! command -v amazon-linux-extras 2>&1 >/dev/null
+          then
+              echo "Installing perl and deps"
+              sudo dnf install -y gpg gcc gcc-c++ make rust patch make bzip2 libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel
+              sudo dnf -y install perl
+          fi
           curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
           export PATH=~/.rbenv/bin/:~/.rbenv/shims:$PATH
           curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-doctor | bash
@@ -31,9 +37,10 @@ lang_variant:
 
 weblog:
     name: test-app-ruby
-    # centos_7_amd64, redhat_8_6, & fedora are excluded because they do not provide the right Ruby versions
+    # fedora are excluded because they do not provide the right Ruby versions
     # TODO oracle_linux and alma_linux. Failed when we run the app. Related with how we install Ruby
-    excluded_os_branches: [ oracle_linux, alma_linux, fedora]
+    #Ubuntu_18_amd64, ubuntu 20: installation fails
+    excluded_os_branches: [Ubuntu_18_amd64,ubuntu20_amd64, ubuntu20_arm64, oracle_linux, alma_linux, fedora]
     install:
       - os_type: linux
 
