check failed pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -146,9 +146,14 @@ check_pipeline_status:
   image: registry.ddbuild.io/images/ci_docker_base
   tags: ["runner:docker"]
   script:
-    - echo "Checking if any job failed... $CI_PIPELINE_STATUS"
-    - if [ "$CI_PIPELINE_STATUS" = "failed" ]; then exit 1; fi 
-
+    - echo "Checking if any job failed..."
+    - |
+      FAILED_JOBS=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
+      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs?scope=failed" | jq '. | length')
+    - if [ "$FAILED_JOBS" -gt 0 ]; then
+        echo "❌ A job failed, failing the pipeline!";
+        exit 1;
+      fi
   when: always
 
 check_merge_labels:
