try with personal token

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -158,10 +158,15 @@ check_pipeline_status:
    tags: ["runner:docker"]
    script:
      - echo "Checking if any job failed..."
+     - export GITLAB_TOKEN=$(aws ssm get-parameter --region us-east-1 --name "ci.$CI_PROJECT_NAME.gitlab.token" --with-decryption --query "Parameter.Value" --out text)
      - |
-       FAILED_JOBS=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs?scope=failed")
-     - echo "URL $CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs?scope=failed"
-     - echo "OUTPUT  $FAILED_JOBS"
+       FAILED_JOBS=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
+       "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs?scope=failed" | jq '. | length')
+     - if [ "$FAILED_JOBS" -gt 0 ]; then
+         echo "❌ A job failed, failing the pipeline!";
+         echo "Failing Jobs [$FAILED_JOBS]";
+         exit 1;
+       fi
    when: always
 
 check_merge_labels:
