Debug the failing jobs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -149,6 +149,8 @@ check_pipeline_status:
     - |
       RETRIES=3
       FAILED_JOBS=0
+      FAILED_JOB_DETAILS=""
+
       for i in $(seq 1 $RETRIES); do
         RESPONSE=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
         "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs?scope=failed")
@@ -156,24 +158,28 @@ check_pipeline_status:
         # Ensure response is valid JSON before parsing
         if echo "$RESPONSE" | jq empty > /dev/null 2>&1; then
           FAILED_JOBS=$(echo "$RESPONSE" | jq '. | length')
+
           if [ "$FAILED_JOBS" -eq 0 ]; then
             echo "✅ No failed jobs detected."
             exit 0
           fi
+
+          # Extract failing job details
+          FAILED_JOB_DETAILS=$(echo "$RESPONSE" | jq -r '.[] | "Job ID: \(.id), Name: \(.name), Status: \(.status), Stage: \(.stage), URL: '"\"$CI_PROJECT_URL/-/jobs/\(.id)\""' "')
+          
+          break  # Exit loop if valid response received
         else
           echo "⚠️ Warning: Received invalid JSON response, retrying... ($i/$RETRIES)"
           sleep 5  # Wait before retrying
         fi
       done
 
-    - |
-      if [ "$FAILED_JOBS" -gt 0 ]; then
-        echo "❌ A job failed, failing the pipeline!";
-        echo "Failing Jobs: [$FAILED_JOBS]";
-        exit 1;
-      fi
+    - echo "❌ A job failed, failing the pipeline!"
+    - echo "Failing Jobs: [$FAILED_JOBS]"
+    - echo "Details of failed jobs:"
+    - echo "$FAILED_JOB_DETAILS"
+    - exit 1
   when: always
-
 
 check_merge_labels:
   #Build docker images if it's needed. Check if the PR has the labels associated with the image build.
