Fix format

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -12,7 +12,7 @@ stages:
   - system-tests-utils
 
 variables:
-  TEST: 1
+    TEST: 1
 
 compute_pipeline:
   image: registry.ddbuild.io/ci/libdatadog-build/system-tests:57161036
@@ -64,7 +64,7 @@ compute_pipeline:
       fi
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   artifacts:
     paths:
       - nodejs_ssi_gitlab_pipeline.yml
@@ -86,7 +86,7 @@ nodejs_ssi_pipeline:
     strategy: depend
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   when: always
 
 java_ssi_pipeline:
@@ -101,7 +101,7 @@ java_ssi_pipeline:
     strategy: depend
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   when: always
 
 dotnet_ssi_pipeline:
@@ -116,7 +116,7 @@ dotnet_ssi_pipeline:
     strategy: depend
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   when: always
 
 python_ssi_pipeline:
@@ -131,7 +131,7 @@ python_ssi_pipeline:
     strategy: depend
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   when: always
 
 php_ssi_pipeline:
@@ -146,7 +146,7 @@ php_ssi_pipeline:
     strategy: depend
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   when: always
 
 ruby_ssi_pipeline:
@@ -161,7 +161,7 @@ ruby_ssi_pipeline:
     strategy: depend
   rules:
     - if: '$SCHEDULED_JOB == ""'
-    - if: "$SCHEDULED_JOB == null"
+    - if: '$SCHEDULED_JOB == null'
   when: always
 
 delete_amis:
@@ -172,9 +172,9 @@ delete_amis:
     AMI_RETENTION_DAYS: 10
     AMI_LAST_LAUNCHED_DAYS: 10
   script:
-    - ./build.sh -i runner
-    - source venv/bin/activate
-    - python utils/scripts/pulumi_clean_up.py --component amis --ami-retention-days $AMI_RETENTION_DAYS --ami-last-launched-days $AMI_LAST_LAUNCHED_DAYS
+        - ./build.sh -i runner
+        - source venv/bin/activate
+        - python utils/scripts/pulumi_clean_up.py --component amis --ami-retention-days $AMI_RETENTION_DAYS --ami-last-launched-days $AMI_LAST_LAUNCHED_DAYS
   rules:
     - if: '$SCHEDULED_JOB == "delete_amis"'
   after_script: echo "Finish"
@@ -185,27 +185,27 @@ delete_amis_by_name_or_lang:
   stage: system-tests-utils
   allow_failure: false
   script:
-    - |
-      if [ -z "$AMI_NAME" ] && [ -z "$AMI_LANG" ]; then
-        echo "❌ ERROR: Either AMI_NAME or AMI_LANG must be set."
-        exit 1
-      fi
-      echo "✅ Proceeding with AMI_NAME=$AMI_NAME, AMI_LANG=$AMI_LANG"
-    - ./build.sh -i runner
-    - source venv/bin/activate
-    - |
-      CMD="python utils/scripts/pulumi_clean_up.py --component amis_by_name"
+        - |
+          if [ -z "$AMI_NAME" ] && [ -z "$AMI_LANG" ]; then
+            echo "❌ ERROR: Either AMI_NAME or AMI_LANG must be set."
+            exit 1
+          fi
+          echo "✅ Proceeding with AMI_NAME=$AMI_NAME, AMI_LANG=$AMI_LANG"
+        - ./build.sh -i runner
+        - source venv/bin/activate
+        - |
+          CMD="python utils/scripts/pulumi_clean_up.py --component amis_by_name"
 
-      if [ -n "$AMI_NAME" ]; then
-        CMD="$CMD --ami-name $AMI_NAME"
-      fi
+          if [ -n "$AMI_NAME" ]; then
+            CMD="$CMD --ami-name $AMI_NAME"
+          fi
 
-      if [ -n "$AMI_LANG" ]; then
-        CMD="$CMD --ami-lang $AMI_LANG"
-      fi
+          if [ -n "$AMI_LANG" ]; then
+            CMD="$CMD --ami-lang $AMI_LANG"
+          fi
 
-      echo "Running: $CMD"
-      eval $CMD
+          echo "Running: $CMD"
+          eval $CMD
   rules:
     - if: '$SCHEDULED_JOB == "delete_amis_by_name_or_lang"'
   after_script: echo "Finish"
@@ -217,9 +217,9 @@ delete_ec2_instances:
   variables:
     EC2_AGE_MINUTES: 45
   script:
-    - ./build.sh -i runner
-    - source venv/bin/activate
-    - python utils/scripts/pulumi_clean_up.py --component ec2 --ec2-age-minutes $EC2_AGE_MINUTES
+        - ./build.sh -i runner
+        - source venv/bin/activate
+        - python utils/scripts/pulumi_clean_up.py --component ec2 --ec2-age-minutes $EC2_AGE_MINUTES
   rules:
     - if: '$SCHEDULED_JOB == "delete_ec2_instances"'
   after_script: echo "Finish"
@@ -229,9 +229,9 @@ count_amis:
   stage: system-tests-utils
   allow_failure: false
   script:
-    - ./build.sh -i runner
-    - source venv/bin/activate
-    - python utils/scripts/pulumi_clean_up.py --component amis_count
+        - ./build.sh -i runner
+        - source venv/bin/activate
+        - python utils/scripts/pulumi_clean_up.py --component amis_count
   rules:
     - if: '$SCHEDULED_JOB == "count_amis"'
   after_script: echo "Finish"
@@ -272,8 +272,8 @@ generate_system_tests_lambda_proxy_image:
     - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass-write --with-decryption --query "Parameter.Value" --out text)
     - echo "$DOCKER_LOGIN_PASS" | docker login --username "$DOCKER_LOGIN" --password-stdin
   script:
-    - ./build.sh -i lambda-proxy
-    - docker push datadog/system-tests:lambda-proxy-v1
+      - ./build.sh -i lambda-proxy
+      - docker push datadog/system-tests:lambda-proxy-v1
   rules:
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
       changes:
@@ -289,16 +289,16 @@ generate_system_tests_lib_injection_images:
     PRIVATE_DOCKER_REGISTRY: 235494822917.dkr.ecr.us-east-1.amazonaws.com
     PRIVATE_DOCKER_REGISTRY_USER: AWS
   script:
-    - aws ecr get-login-password | docker login --username ${PRIVATE_DOCKER_REGISTRY_USER} --password-stdin ${PRIVATE_DOCKER_REGISTRY}
-    - ./lib-injection/build/build_lib_injection_images.sh $PRIVATE_DOCKER_REGISTRY
+      - aws ecr get-login-password | docker login --username ${PRIVATE_DOCKER_REGISTRY_USER} --password-stdin ${PRIVATE_DOCKER_REGISTRY}
+      - ./lib-injection/build/build_lib_injection_images.sh $PRIVATE_DOCKER_REGISTRY
   rules:
     - if: '$SCHEDULED_JOB == "generate_system_tests_lib_injection_images"'
     - when: manual
 
 .delayed_base_job:
-  image: registry.ddbuild.io/ci/libdatadog-build/ci_docker_base:67145216
-  tags: ["arch:amd64"]
-  script:
-    - echo "⏳ Waiting before triggering the child pipeline..."
-  when: delayed
-  start_in: 5 minutes
+    image: registry.ddbuild.io/ci/libdatadog-build/ci_docker_base:67145216
+    tags: ["arch:amd64"]
+    script:
+        - echo "⏳ Waiting before triggering the child pipeline..."
+    when: delayed
+    start_in: 5 minutes
