Limmited to 50MB

diff --git a/.gitlab/ssi_gitlab-ci.yml b/.gitlab/ssi_gitlab-ci.yml
--- a/.gitlab/ssi_gitlab-ci.yml
+++ b/.gitlab/ssi_gitlab-ci.yml
@@ -111,9 +111,9 @@ ssi_tests:
             AWS_CONSOLE_URL="https://s3.console.aws.amazon.com/s3/buckets/${S3_BUCKET}?region=us-east-1&prefix=${EXECUTION_UNIQUE_IDENTIFIER}/${LAST_DIRECTORY}/${VM}_${WEBLOG}/"
             echo "S3 logs URL (AWS Console): ${AWS_CONSOLE_URL}"
 
-            # Delete large files (>100MB) to avoid CI/CD archiving
+            # Delete large files (>50MB) to avoid CI/CD archiving
             echo "Deleting large files to avoid CI/CD archiving..."
-            find "$LOGS_FOLDER" -type f -size +100M -exec sh -c 'echo "Deleting large file ($(du -h "$1" | cut -f1)): $1" && rm "$1"' _ {} \; || echo "Failed to delete some large files"
+            find "$LOGS_FOLDER" -type f -size +50M -exec sh -c 'echo "Deleting large file ($(du -h "$1" | cut -f1)): $1" && rm "$1"' _ {} \; || echo "Failed to delete some large files"
         fi
 
         # Logs to be archived by gitlab
