docker logs fix permissions

diff --git a/.gitlab/ssi_gitlab-ci.yml b/.gitlab/ssi_gitlab-ci.yml
--- a/.gitlab/ssi_gitlab-ci.yml
+++ b/.gitlab/ssi_gitlab-ci.yml
@@ -105,7 +105,7 @@ ssi_tests:
             echo "Local folder: ${LOGS_FOLDER}"
             echo "S3 destination: ${S3_DESTINATION}"
 
-            aws s3 cp "$LOGS_FOLDER" "$S3_DESTINATION" --recursive || echo "Failed to upload logs to S3"
+            aws s3 cp "$LOGS_FOLDER" "$S3_DESTINATION" --recursive --quiet || echo "Failed to upload logs to S3"
 
             # Generate AWS Console URL for the uploaded folder
             AWS_CONSOLE_URL="https://s3.console.aws.amazon.com/s3/buckets/${S3_BUCKET}?region=us-east-1&prefix=${EXECUTION_UNIQUE_IDENTIFIER}/${LAST_DIRECTORY}/${VM}_${WEBLOG}/"
