fix some linting issues

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,6 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-
   lint:
     runs-on: ubuntu-latest
     steps:
@@ -32,17 +31,17 @@ jobs:
     name: Test the test
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install runner
-        uses: ./.github/actions/install_runner
-      # force /bin/bash in order to test against bash 3.2 on macOS
-      - name: Test the test (direct)
-        run: /bin/bash run.sh TEST_THE_TEST
-      - name: Test group parsing
-        run: |
-          /bin/bash run.sh ++dry APPSEC_SCENARIOS
-          /bin/bash run.sh ++dry TRACER_RELEASE_SCENARIOS
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: Install runner
+      uses: ./.github/actions/install_runner
+    # force /bin/bash in order to test against bash 3.2 on macOS
+    - name: Test the test (direct)
+      run: /bin/bash run.sh TEST_THE_TEST
+    - name: Test group parsing
+      run: |
+        /bin/bash run.sh ++dry APPSEC_SCENARIOS
+        /bin/bash run.sh ++dry TRACER_RELEASE_SCENARIOS
 
   scenarios:
     name: Get scenarios and groups
@@ -55,14 +54,14 @@ jobs:
   fail-if-target-branch:
     name: Fail if target branch is specified
     needs:
-      - impacted_libraries
+    - impacted_libraries
     if: needs.impacted_libraries.outputs.target-branch != ''
     runs-on: ubuntu-latest
     steps:
-      - name: Fail if PR title contains a target branch
-        run: |
-          echo "This PR can't be merged, due to the title specifying a target branch"
-          exit 1
+    - name: Fail if PR title contains a target branch
+      run: |
+        echo "This PR can't be merged, due to the title specifying a target branch"
+        exit 1
 
   system_tests:
     name: System Tests
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,9 +13,9 @@ stages:
   - system-tests-utils
 
 variables:
-    # Do not modify this - must be the repository name for Kubernetes gitlab runners to run
-    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: system-tests #helm-charts
-    TEST: 1
+  # Do not modify this - must be the repository name for Kubernetes gitlab runners to run
+  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: system-tests #helm-charts
+  TEST: 1
 
 compute_pipeline:
   image: registry.ddbuild.io/ci/libdatadog-build/system-tests:57161036
@@ -239,9 +239,9 @@ delete_amis:
     AMI_RETENTION_DAYS: 10
     AMI_LAST_LAUNCHED_DAYS: 10
   script:
-        - ./build.sh -i runner
-        - source venv/bin/activate
-        - python utils/scripts/pulumi_clean_up.py --component amis --ami-retention-days $AMI_RETENTION_DAYS --ami-last-launched-days $AMI_LAST_LAUNCHED_DAYS
+    - ./build.sh -i runner
+    - source venv/bin/activate
+    - python utils/scripts/pulumi_clean_up.py --component amis --ami-retention-days $AMI_RETENTION_DAYS --ami-last-launched-days $AMI_LAST_LAUNCHED_DAYS
   rules:
     - if: '$SCHEDULED_JOB == "delete_amis"'
   after_script: echo "Finish"
@@ -252,27 +252,27 @@ delete_amis_by_name_or_lang:
   stage: system-tests-utils
   allow_failure: false
   script:
-        - |
-          if [ -z "$AMI_NAME" ] && [ -z "$AMI_LANG" ]; then
-            echo "❌ ERROR: Either AMI_NAME or AMI_LANG must be set."
-            exit 1
-          fi
-          echo "✅ Proceeding with AMI_NAME=$AMI_NAME, AMI_LANG=$AMI_LANG"
-        - ./build.sh -i runner
-        - source venv/bin/activate
-        - |
-          CMD="python utils/scripts/pulumi_clean_up.py --component amis_by_name"
+    - |
+      if [ -z "$AMI_NAME" ] && [ -z "$AMI_LANG" ]; then
+        echo "❌ ERROR: Either AMI_NAME or AMI_LANG must be set."
+        exit 1
+      fi
+      echo "✅ Proceeding with AMI_NAME=$AMI_NAME, AMI_LANG=$AMI_LANG"
+    - ./build.sh -i runner
+    - source venv/bin/activate
+    - |
+      CMD="python utils/scripts/pulumi_clean_up.py --component amis_by_name"
 
-          if [ -n "$AMI_NAME" ]; then
-            CMD="$CMD --ami-name $AMI_NAME"
-          fi
+      if [ -n "$AMI_NAME" ]; then
+        CMD="$CMD --ami-name $AMI_NAME"
+      fi
 
-          if [ -n "$AMI_LANG" ]; then
-            CMD="$CMD --ami-lang $AMI_LANG"
-          fi
+      if [ -n "$AMI_LANG" ]; then
+        CMD="$CMD --ami-lang $AMI_LANG"
+      fi
 
-          echo "Running: $CMD"
-          eval $CMD
+      echo "Running: $CMD"
+      eval $CMD
   rules:
     - if: '$SCHEDULED_JOB == "delete_amis_by_name_or_lang"'
   after_script: echo "Finish"
@@ -284,9 +284,9 @@ delete_ec2_instances:
   variables:
     EC2_AGE_MINUTES: 45
   script:
-        - ./build.sh -i runner
-        - source venv/bin/activate
-        - python utils/scripts/pulumi_clean_up.py --component ec2 --ec2-age-minutes $EC2_AGE_MINUTES
+    - ./build.sh -i runner
+    - source venv/bin/activate
+    - python utils/scripts/pulumi_clean_up.py --component ec2 --ec2-age-minutes $EC2_AGE_MINUTES
   rules:
     - if: '$SCHEDULED_JOB == "delete_ec2_instances"'
   after_script: echo "Finish"
@@ -296,9 +296,9 @@ count_amis:
   stage: system-tests-utils
   allow_failure: false
   script:
-        - ./build.sh -i runner
-        - source venv/bin/activate
-        - python utils/scripts/pulumi_clean_up.py --component amis_count
+    - ./build.sh -i runner
+    - source venv/bin/activate
+    - python utils/scripts/pulumi_clean_up.py --component amis_count
   rules:
     - if: '$SCHEDULED_JOB == "count_amis"'
   after_script: echo "Finish"
@@ -315,7 +315,7 @@ check_merge_labels:
     - export DOCKER_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-write --with-decryption --query "Parameter.Value" --out text)
     - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass-write --with-decryption --query "Parameter.Value" --out text)
   script:
-    -  echo $GH_TOKEN | docker login ghcr.io -u publisher --password-stdin
+    - echo $GH_TOKEN | docker login ghcr.io -u publisher --password-stdin
     - ./utils/scripts/get_pr_merged_labels.sh
   rules:
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
@@ -331,16 +331,16 @@ generate_system_tests_images:
     - export DOCKER_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-write --with-decryption --query "Parameter.Value" --out text)
     - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass-write --with-decryption --query "Parameter.Value" --out text)
   script:
-      -  echo $GH_TOKEN | docker login ghcr.io -u publisher --password-stdin
-      - ./utils/build/build_tracer_buddies.sh --push
-      - ./utils/build/build_python_base_images.sh --push
-      - ./lib-injection/build/build_lib_injection_images.sh
+    - echo $GH_TOKEN | docker login ghcr.io -u publisher --password-stdin
+    - ./utils/build/build_tracer_buddies.sh --push
+    - ./utils/build/build_python_base_images.sh --push
+    - ./lib-injection/build/build_lib_injection_images.sh
   when: manual
 
 .delayed_base_job:
-    image: registry.ddbuild.io/images/ci_docker_base
-    tags: ["arch:amd64"]
-    script:
-        - echo "⏳ Waiting before triggering the child pipeline..."
-    when: delayed
-    start_in: 5 minutes
+  image: registry.ddbuild.io/images/ci_docker_base
+  tags: ["arch:amd64"]
+  script:
+    - echo "⏳ Waiting before triggering the child pipeline..."
+  when: delayed
+  start_in: 5 minutes
